//: Playground - noun: a place where people can play

//var cc = CalculatorCore()
//cc.execute(Add(10))
//cc.execute(Minus(5))
//cc.execute(Multiply(5))
//cc.execute(Divide(25))
//print(cc.value)

//var c = Calculator()
//c.push(1)
//c.push(0)
//c.push(0)
//c.execute(.Add)
//c.push(1)
//c.push(0)
//c.execute(.Minus)
//print(c.core.value)
//c.push(2)
//c.push(0)
//print(c.core.value)

//c.push(5)
//c.push(0)
//c.push(7)
//c.pop()
//c.executeAdd()
//print(c.core.value)
//c.push(7)
//c.push(9)
//c.executeFlush()
//c.executeFlush()
//c.executeFlush()
//c.executeFlush()
//print(c.core.value)
//c.push(5)
//c.markDecimal()
//c.push(0)
//c.push(8)
//print(c.decimalPosition)
